import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";
import "@/styles/globals.css";
import { cookies } from "next/headers";
import { RequestCookie } from "next/dist/compiled/@edge-runtime/cookies";
import LayoutWrapper from "./LayoutWrapper";
import React from "react";

const inter = Inter({ subsets: ["latin"] });
const notoSans = Noto_Sans_KR({
  preload: false,
  style: "normal",
});

export const metadata: Metadata = {
  title: "Toeicdoit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body className={`${inter.className} ${notoSans.className}`}>
        <div className="bg-white overflow-hidden">
          <LayoutWrapper>
            {modal}
            {children}
          </LayoutWrapper>
        </div>
      </body>
    </html>
  );
}
